### ISSUE TITLE
System.InvalidOperationException: Cannot get all Sandbox assemblies: wrappers are not bound.

### ISSUE THREAD

**Issue by Claw256** [Erlite/Sandbox.Bootstrap#1]
I'm getting an error when I try to load the DLL assembly that is included with this repo, as well as a custom DLL assembly for the latest S&box version, inside a sample S&box addon. The error in the S&box logs says:
```
Failed to load assembly 'MyBootstrappedAddon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' at 'MyBootstrappedAddon'	System.InvalidOperationException: Cannot get all Sandbox assemblies: wrappers are not bound.
   at Sandbox.Bootstrap.BootstrapInterface.GetSandboxAssemblies() in D:\Games\Steam\steamapps\common\sbox\addons\Sandbox.Bootstrap\code\BootstrapInterface.cs:line 158
   at Sandbox.Bootstrap.Bootstrapper.Boot(BootstrappedAddonBuilder bootstrapBuilder) in D:\Games\Steam\steamapps\common\sbox\addons\Sandbox.Bootstrap\code\Bootstrapper.cs:line 86
```
And in the in-game S&box console, it says the Bootstrapper is out of date, and it could not retrieve Global.GameInterface:
```
ExecuteQueuedCreation() took 247032us [ Spawned: 748, Activated 748, PostDataUpdate: 0, Destroyed: 0, Deallocated: 0, PvsUpdate: 0 ]
"Rexami" has joined the game
Initializing.
Initializing Sandbox.Bootstrap.MonoCecil.dll
Succesfully loaded, ready to modify assembly references.
Wrapping Sandbox internals using Reflection.
Bootstrapper is out of date! Could not retrieve Global.GameInterface!
Loading assembly at 'MyBootstrappedAddon'
Found assembly 'MyBootstrappedAddon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' at 'bootstrapped/MyBootstrappedAddon/MyBootstrappedAddon.dll', attempting to load.
Valid filesystem: True
Relative path: bootstrapped/MyBootstrappedAddon/MyBootstrappedAddon.dll
Absolute path: D:\Games\Steam\steamapps\common\sbox\addons\Sandbox.Bootstrap\bootstrapped\MyBootstrappedAddon\MyBootstrappedAddon.dll
bootstrapBuilder.AssemblyName: MyBootstrappedAddon
[Sandbox.Bootstrap.MonoCecil] Attempting to override references.
Failed to load assembly 'MyBootstrappedAddon, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' at 'MyBootstrappedAddon'
```
Here is what my addon code looks like (It's just the sbox-minimal gamemode on Facepunch's GitHub dropped into the bootstrap addon from this github):

`MinimalGame.cs`:
```
using Sandbox;
using Sandbox.UI.Construct;
using System;
using System.IO;
using System.Threading.Tasks;
using Sandbox.Bootstrap;
using Activator = System.Activator;

//
// You don't need to put things in a namespace, but it doesn't hurt.
//
namespace MinimalExample
{

	/// <summary>
	/// This is your game class. This is an entity that is created serverside when
	/// the game starts, and is replicated to the client. 
	/// 
	/// You can use this to create things like HUDs and declare which player class
	/// to use for spawned players.
	/// </summary>
	public partial class MinimalGame : Sandbox.Game
	{
		public MinimalGame()
		{
			if ( IsServer )
			{
				Log.Info( "My Gamemode Has Created Serverside!" );

				// Create a HUD entity. This entity is globally networked
				// and when it is created clientside it creates the actual
				// UI panels. You don't have to create your HUD via an entity,
				// this just feels like a nice neat way to do it.
				new MinimalHudEntity();
			}

			if ( IsClient )
			{
				Log.Info( "My Gamemode Has Created Clientside!" );
			}
		}

		/// <summary>
		/// A client has joined the server. Make them a pawn to play with
		/// </summary>
		public override void ClientJoined( Client client )
		{
			base.ClientJoined( client );

			var player = new MinimalPlayer();
			client.Pawn = player;
			var assembly = new BootstrappedAddonBuilder()
				.WithAssemblyName( "MyBootstrappedAddon" ) // The bootstrapped addon assembly.
				.OnLoaded( asm =>
				{
					try
					{
						Activator.CreateInstance( asm.FullName!, "MyBootstrappedAddon.Class1" );
					}
					catch (Exception e)
					{
						Log.Error(e, "Failed to activate Class1");
					}
				})
				.Bootstrap();
			var MutagenAssem = new BootstrappedAddonBuilder()
				.WithAssemblyName( "Mutagen.Bethesda" ) // The bootstrapped addon assembly.
				.OnLoaded( asm =>
				{
					try
					{
						Activator.CreateInstance( asm.FullName!, "Mutagen.Bethesda" );
					}
					catch (Exception e)
					{
						Log.Error(e, "Failed to activate Bethesda");
					}
				})
				.Bootstrap();
			var type = MutagenAssem.GetType();
			Log.Info($"The type of the Custom MutagenAssem is: {type}");
			
			player.Respawn();
		}
	}
}
```
Here's what my IDE looks like:
![rider64_LSvcLfyAKv](https://user-images.githubusercontent.com/31168189/147283473-9efb2d70-609a-4c3a-8537-c93e45c6d0be.png)

Any help with this issue would be greatly appreciated.

**Comment by Claw256** [comment]
Also here is my S&Box log:
[Log.log](https://github.com/Erlite/Sandbox.Bootstrap/files/7771048/Log.log)
